mixed-port: 7890
# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# Set to true to allow connections to the local-end server from
# other LAN IP addresses
allow-lan: true

# This is only applicable when `allow-lan` is `true`
# '*': bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
bind-address: "*"

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
log-level: warning

# When set to false, resolver won't translate hostnames to IPv6 addresses
# ipv6: false

# RESTful web API listening address
external-controller: 127.0.0.1:7891

# A relative path to the configuration directory or an absolute path to a
# directory in which you put some static web resource. Clash core will then
# serve it at `http://{{external-controller}}/ui`.
external-ui: /home/idea/.config/oh-my-clash/tools/cd

# Secret for the RESTful API (optional)
# Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
# ALWAYS set a secret if RESTful API is listening on 0.0.0.0
# secret: ""

# Static hosts for DNS server and connection establishment (like /etc/hosts)
#
# Wildcard hostnames are supported (e.g. *.clash.dev, *.foo.*.example.com)
# Non-wildcard domain names have a higher priority than wildcard domain names
# e.g. foo.example.com > *.example.com > .example.com
# P.S. +.foo.com equals to .foo.com and foo.com
hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  # ipv6: true
  # listen: 0.0.0.0:53
  listen: 127.0.0.1:53
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 119.29.29.29
    - "https://120.53.53.53/dns-query"
    - "https://1.12.12.12/dns-query"
    - "https://doh.pub/dns-query"
    - tls://120.53.53.53:853
    - tls://1.12.12.12:853
    - tls://dot.pub:853
    - 223.5.5.5
    - "https://223.5.5.5/dns-query"

tun:
  enable: true
  stack: system # or gvisor
  # dns-hijack:
  #   - 8.8.8.8:53
  #   - tcp://8.8.8.8:53
  #   - any:53
  #   - tcp://any:53
  auto-route: true
  auto-detect-interface: true

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - 自动选择-all
      - 手动选择-all
      - 故障转移
      - DIRECT
      - 机场1-auto
      - 机场2-auto
      - 机场3-auto
      - 机场1
      - 机场2
      - 机场3

  - name: 自动选择-all
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    tolerance: 50
    use:
      - jichang1
      - jichang2
      - jichang3

  - name: 手动选择-all
    type: select
    use:
      - jichang1
      - jichang2
      - jichang3

  - name: 机场1-auto
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    tolerance: 50
    use:
      - jichang1
  - name: 机场2-auto
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    tolerance: 50
    use:
      - jichang2

  - name: 机场3-auto
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    tolerance: 50
    use:
      - jichang3

  - name: 机场1
    type: select
    use:
      - jichang1

  - name: 机场2
    type: select
    use:
      - jichang2

  - name: 机场3
    type: select
    use:
      - jichang3

  - name: 故障转移
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    tolerance: 50
    proxies:
      - 机场1-auto
      - 机场2-auto
      - 机场3-auto

  - name: 漏网之鱼
    type: select
    proxies:
      - PROXY
      - DIRECT

  # load-balance: The request of the same eTLD+1 will be dial to the same proxy.
  - name: 负载均衡-all
    type: load-balance
    use:
      - jichang1
      - jichang2
      - jichang3
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    tolerance: 50
  - name: 机场1-负载均衡
    type: load-balance
    use:
      - jichang1
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    tolerance: 50
  - name: 机场2-负载均衡
    type: load-balance
    use:
      - jichang2

    url: "http://www.gstatic.com/generate_204"
    interval: 300
    tolerance: 50
  - name: 机场3-负载均衡
    type: load-balance
    use:
      - jichang3
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    tolerance: 50

proxy-providers:
  # jichang1:
  #   type: file
  #   path: ./profile/jichang1.yaml
  #   health-check:
  #     enable: true
  #     interval: 600
  #     url: http://www.gstatic.com/generate_204
  # jichang2:
  #   type: file
  #   path: ./profile/jichang2.yaml
  #   health-check:
  #     enable: true
  #     interval: 600
  #     url: http://www.gstatic.com/generate_204
  # jichang3:
  #   type: file
  #   path: ./profile/jichang3.yaml
  #   health-check:
  #     enable: true
  #     interval: 600
  #     url: http://www.gstatic.com/generate_204

  # https://www.urlencoder.org/
  # https://acl4ssr-sub.github.io/
  jichang1:
    type: http
    url: "https://sub.xeton.dev/sub?target=clash&url=<URL-encoded format>&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Mini.ini&emoji=true&list=true&tfo=false&scv=false&fdn=false&sort=false&new_name=true"
    interval: 3600
    path: ./profile/online/jichang1.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  jichang2:
    type: http
    url: "https://sub.xeton.dev/sub?target=clash&url=<URL-encoded format>&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Mini.ini&emoji=true&list=true&tfo=false&scv=false&fdn=false&sort=false&new_name=true"
    interval: 3600
    path: ./profile/online/jichang2.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  jichang3:
    type: http
    url: "https://sub.xeton.dev/sub?target=clash&url=<URL-encoded format>&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Mini.ini&emoji=true&list=true&tfo=false&scv=false&fdn=false&sort=false&new_name=true"
    interval: 3600
    path: ./profile/online/jichang3.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

rule-providers:
  reject:
    type: http
    behavior: domain
    url: https://cdn.staticaly.com/gh/Loyalsoldier/clash-rules/release/reject.txt
    path: ./ruleset/reject.yaml
    interval: 86400
  icloud:
    type: http
    behavior: domain
    url: https://cdn.staticaly.com/gh/Loyalsoldier/clash-rules/release/icloud.txt
    path: ./ruleset/icloud.yaml
    interval: 86400
  apple:
    type: http
    behavior: domain
    url: https://cdn.staticaly.com/gh/Loyalsoldier/clash-rules/release/apple.txt
    path: ./ruleset/apple.yaml
    interval: 86400
  google:
    type: http
    behavior: domain
    url: https://cdn.staticaly.com/gh/Loyalsoldier/clash-rules/release/google.txt
    path: ./ruleset/google.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: https://cdn.staticaly.com/gh/Loyalsoldier/clash-rules/release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: https://cdn.staticaly.com/gh/Loyalsoldier/clash-rules/release/private.txt
    path: ./ruleset/private.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: https://cdn.staticaly.com/gh/Loyalsoldier/clash-rules/release/direct.txt
    path: ./ruleset/direct.yaml
    interval: 86400
  applications:
    type: http
    behavior: classical
    url: https://cdn.staticaly.com/gh/Loyalsoldier/clash-rules/release/applications.txt
    path: ./ruleset/applications.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: https://cdn.staticaly.com/gh/Loyalsoldier/clash-rules/release/cncidr.txt
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: https://cdn.staticaly.com/gh/Loyalsoldier/clash-rules/release/lancidr.txt
    path: ./ruleset/lancidr.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: https://cdn.staticaly.com/gh/Loyalsoldier/clash-rules/release/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.staticaly.com/gh/Loyalsoldier/clash-rules/release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: "https://cdn.staticaly.com/gh/Loyalsoldier/clash-rules/release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400
  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.staticaly.com/gh/Loyalsoldier/clash-rules/release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

rules:
  - IP-CIDR,1.0.0.1/32,DIRECT
  - IP-CIDR,101.101.101.101/32,DIRECT
  - IP-CIDR,8.8.8.8/32,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,applications,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT
  - RULE-SET,telegramcidr,PROXY
  - RULE-SET,proxy,PROXY
  - RULE-SET,gfw,PROXY
  - RULE-SET,greatfire,PROXY
  - GEOIP,CN,DIRECT
  # - GEOIP,HK,DIRECT
  # - GEOIP,TW,DIRECT
  - MATCH,PROXY
  # - "MATCH,漏网之鱼"
