
##vimrc
set nu

if has("autocmd")
    autocmd FileType javascript setlocal ts=4 sts=4 sw=4 expandtab
    autocmd FileType python setlocal ts=4 sts=4 sw=4 expandtab
endif


set list
set listchars=tab:▸\ ,eol:¬
